name: 'action-clang-format'
description: 'Check repository using clang-format'
author: 'HorstBaerbel / Bim Overbohm'
branding:
  icon: check-circle
  color: gray-dark
inputs:
  scandir:
    description: 'Scan directory'
    required: false
    default: '.'
  excludedirs:
    description: 'Exclude directories'
    required: false
    default: 'build'
  extensions:
    description: 'File extensions to include in check'
    required: false
    default: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
  style:
      description: 'Style string'
      required: false
      default: 'file'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.scandir }}
    - ${{ inputs.excludedirs }}
    - ${{ inputs.extensions }}
    - ${{ inputs.style }}